name: Build and upload to PyPI

on:
  push:
    tags: ['*']

jobs:
  build_wheels:
    name: Build on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
      - uses: pypa/cibuildwheel@v2.10.0
        name: Build wheels
        env:
          CIBW_ARCHS_LINUX: x86_64
          CIBW_ARCHS_WINDOWS: AMD64
          CIBW_ARCHS_MACOS: x86_64 universal2
          CIBW_SKIP: >-
            cp37-macosx_universal2
            cp38-macosx_x86_64
            cp38-{win,*linux}*
            cp3{6,9,10,11}-*
            pp3?-*
        with:
          output-dir: dist
      - uses: actions/upload-artifact@v3
        name: Upload wheel artifacts
        with:
          path: dist/*.whl

  upload_pypi:
    name: Upload wheels to PyPI
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        name: Download wheel artifacts
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@v1.5.1
        name: Publish to PyPI
        with:
          user: __token__
          password: ${{secrets.PYPI_TOKEN}}
